### PR TITLE
Add package: chocolate-doom

### PR DESCRIPTION
**Pull request by WMCB-Tech**
This package allows users to run WAD files such as Doom, Hexen, Heretic, etc,

Of course, for better experience, Samsung DeX or External VNC Display with mouse and keyboard is recommended

### CODE REVIEW

**Comment by WMCB-Tech** [comment]
Hmmm, the CI logs says that it can't run C compiled programs, but when i compile it on my device, it works fine
<details>
  <summary>Last CI Logs</summary>
 ```
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for gcc... x86_64-linux-android-clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
configure: error: in `/home/builder/.termux-build/chocolate-doom/src':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
checking whether we are cross compiling... 
Error: Process completed with exit code 1.
```
</details>

**Comment by xeffyr** [comment]
On-device != on CI. Its Termux vs x86_64 Ubuntu.

Cross-compilation is disabled for some reason for x86_64 build, it assumes that build system and host are same:
```
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
```

**Comment by WMCB-Tech** [comment]
Hmmm, but it can be blacklisted?

**Comment by suhan-paradkar** [comment]
> Hmmm, but it can be blacklisted? (`x86_64` exclusion)
> 
> EDIT: I may specify the `TERMUX_PKG_BLACKLISTED_ARCHES`

That may work..

**Comment by WMCB-Tech** [comment]
Somehow, this error keeps spitting out, even on `arm` `aarch64` `i686`
```
checking build system type... x86_64-pc-linux-gnu
configure.ac:13: installing 'autotools/config.sub'
checking host system type... x86_64-pc-linux-gnu
configure.ac:112: installing 'autotools/install-sh'
checking for gcc... <arch>-linux-android-clang
configure.ac:112: installing 'autotools/missing'
midiproc/Makefile.am: installing 'autotools/depcomp'
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
configure: error: in `/home/builder/.termux-build/chocolate-doom/src':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
```
Any ideas are appreciated

**Comment by xeffyr** [comment]
Here is a culprit: https://github.com/chocolate-doom/chocolate-doom/blob/master/autogen.sh#L4

Please, do not blind copy packaging steps from other `build.sh`. `NOCONFIGURE` won't work there, you need to either patch autogen.sh or run `autoreconf -fi` manually.

**Comment by WMCB-Tech** [comment]
> Here is a culprit: https://github.com/chocolate-doom/chocolate-doom/blob/master/autogen.sh#L4

Ah sh*t, that `autogen.sh` was too simple, some trial and error then

**Comment by suhan-paradkar** [comment]
> > Here is a culprit: https://github.com/chocolate-doom/chocolate-doom/blob/master/autogen.sh#L4
> 
> Ah sh*t, that `autogen.sh` was too simple, didn't realize that, some trial and error then

I wonder if that works in x86_64 then...

**Comment by WMCB-Tech** [comment]
i should try enabling `x86_64` back as both `aarch64` and `i686` as build in `arm` is stalled

probably this time, it should work

**Review by xeffyr — APPROVED** [review]

**Pull request merged**
