### PR TITLE
Updated version of geany

### PR DESCRIPTION
**Pull request by NoNameMan1231**

### CODE REVIEW

**Review by NoNameMan1231 — COMMENTED** [review]
Geany is updated to 1.38

**Comment by AnGelXoG** [comment]
have you changed the sha256?

**Comment by NoNameMan1231** [comment]
> have you changed the sha256?

Oh....no!

**Comment by AnGelXoG** [comment]
XD

**Comment by NoNameMan1231** [comment]
@AnGelXoG 
Fixed in #545

**Pull request closed without merging**
