### PR TITLE
update some xfce4 packages and enable xfce4-screenshooter and file-roller

### PR DESCRIPTION
**Pull request by Yisus7u7**

### CODE REVIEW

**Comment by Yisus7u7** [comment]
@xeffyr 
```bash
termux - build of 'file-roller' done
termux - building xfce4-goodies for arch aarch64...
/home/builder/termux-packages/scripts/build/termux_step_create_debian_package.sh: line 49: AR: unbound variable
Error: Process completed with exit code 1.
```

**Comment by Yisus7u7** [comment]
@xeffyr Done.
The xfce4-goodies meta package cannot be generated due to an error in one of the termux-packages scripts.

You can now merge these changes, still most of the xfce4-goodies components are available.

**Comment by Yisus7u7** [comment]
I want to add some dependencies in the xfce4 meta-package, the bad thing is the error of `termux_step_create_debian_package.sh`

**Comment by Yisus7u7** [comment]
Screenshot_20211202-215121

Update xfce4-panel to 1.16.3

**Comment by Yisus7u7** [comment]
Yeah!

**Comment by Yisus7u7** [comment]
@xeffyr 
You can now merge the changes, everything is ready.

**Comment by Yisus7u7** [comment]
Done

**Comment by Yisus7u7** [comment]
@xeffyr Done! :3

**Review by leapofazzam123 — COMMENTED** [review]
Don't change the maintainer from @termux in enabled packages

**Comment by leapofazzam123** [comment]
Please keep it @termux, not your own name

**Comment by Grimler91** [comment]
> Please keep it @termux, not your own name

It is fine to change the maintainer, assuming that the person intends to keep on working on it (working as in testing, updating, fixing bugs (if any)), @termux is really just a fallback/default value

**Comment by xeffyr** [comment]
**Rebase PR** and enable `xfce4-goodies` subpackage. `build-package.sh` issue should be resolved now.

**Comment by Yisus7u7** [comment]
> Don't change the maintainer from @termux in enabled packages

Those packages were added by me, so I gave them my name again since I was the one who solved them

**Comment by Yisus7u7** [comment]
@xeffyr Done.

**Comment by leapofazzam123** [comment]
> > Please keep it @termux, not your own name
> 
> It is fine to change the maintainer, assuming that the person intends to keep on working on it (working as in testing, updating, fixing bugs (if any)), @termux is really just a fallback/default value

Ah, i didn't know that

**Pull request merged**
