### PR TITLE
Add Package - Xfce Whiskermenu Plugin

### PR DESCRIPTION
**Pull request by WMCB-Tech**
Covers (#279)

### CODE REVIEW

**Comment by WMCB-Tech** [comment]
For some reason the build status on ARM/ARM64 success according to the CI logs but not i686, any ideas?

**Comment by suhan-paradkar** [comment]
It doesn't even work with x86_64.... 
Mostly some problems with libraries.. mostly with libwhiskermenu.so

**Comment by WMCB-Tech** [comment]
Huh, i might try compiling it on i686 myself see if it got errors

**Comment by WMCB-Tech** [comment]
Seems it builds fine on i686

image

but i think i forgot to add `xorgproto`, lemme fix it

**Comment by WMCB-Tech** [comment]
Huh, it the CI says fails to link the `libwhiskermenu.so` library, but when i build it manually, it builds fine, on both `x86_64` and `i386`

**Comment by WMCB-Tech** [comment]
Probably this has something to do with cross-compilation

**Comment by xeffyr** [comment]
It fails because `aarch64-linux-android-strip` is being picked for x86 arches.

**Comment by xeffyr** [comment]
Fails for local build as well.

**Comment by WMCB-Tech** [comment]
huh, so it should be fixable?

**Comment by xeffyr** [comment]
I don't have any clue why it happens. First thought was that issue in `build-package.sh` script, so it incorrectly configures `$STRIP` variable, but that was not the case. All compiler variables look fine. Have also checked stuff in $TERMUX_PREFIX in case if one of x86_64 package dependencies is actually for AArch64, but that was not the case too.

Last thing that could be done is to disable binary stripping during the compile time because this is done anyway during packaging.

**Comment by xeffyr** [comment]
Ok, I have found the issue. `build-package.sh` doesn't define `CMAKE_STRIP` when using `cmake`.

**Pull request merged**
