### PR TITLE
Add package: xpdf

### PR DESCRIPTION
**Pull request by suhan-paradkar**

### CODE REVIEW

**Comment by Yisus7u7** [comment]
@suhan-paradkar

I have a question, to make a package request, I just have to make sure your build works and after that make a script with your information?

**Comment by Yisus7u7** [comment]
Or apart from that folder and the script you have to do something else?

**Comment by Yisus7u7** [comment]
Pd: And how do I get the TERMUX_PKG_SHA256

**Comment by suhan-paradkar** [comment]
> @suhan-paradkar
> 
> I have a question, to make a package request, I just have to make sure your build works and after that make a script with your information?

You mean Pull request??
Yeah.. making sure build works is better.. orelse you can always see github actions...

> @suhan-paradkar
> 
> I have a question, to make a package request, I just have to make sure your build works and after that make a script with your information?

You mean Pull request??
Making sure build works is recommended...
But you can always check that in GitHub action CI

**Comment by suhan-paradkar** [comment]
> Or apart from that folder and the script I have to do something else?

That depends on the package and its requirements

**Comment by Yisus7u7** [comment]
Well, and if there the package is compiled and works normally, I just need to create a folder and a script similar to that with the package info?

**Comment by Yisus7u7** [comment]
Pd and how do I get the TERMUX_PKG_SHA256

**Comment by suhan-paradkar** [comment]
> Pd: And how do I get the TERMUX_PKG_SHA256

```
sha256sum tar_file_of_the_package.tar.gz
```

**Comment by Yisus7u7** [comment]
> > Pd: ¿Y cómo obtengo el TERMUX_PKG_SHA256?
> 
> ```
> sha256sum tar_file_of_the_package.tar.gz
> ```

Oh ok, tanks you

**Comment by suhan-paradkar** [comment]
> Well, and if there the package is compiled and works normally, I just need to create a folder and a script similar to that with the package info?

Yes.. and the folder name becomes the package name of the .deb file
Also.. you need to include the patch files in the same folder... You can see the Contributor's wiki for the same...

**Comment by Yisus7u7** [comment]
Are patches only necessary to fix bugs in the true package?

**Comment by thunder-coding** [comment]
> Are patches only necessary to fix bugs in the true package? 

Nope, see https://github.com/termux/termux-packages/wiki/Common-porting-problems

**Review by xeffyr — APPROVED** [review]

**Pull request merged**
