### PR TITLE
Rebuilding otter-browser

### PR DESCRIPTION
**Pull request by NoNameMan1231**

### CODE REVIEW

**Comment by wmcbtech30** [comment]
Any reasons for this rebuild? your pr doesn't seem to be informational or referencing to the issue for this resolution

**Comment by NoNameMan1231** [comment]
> Any reasons for this rebuild? your pr doesn't seem to be informational or referencing to the issue for this resolution

IMG_20220417_153547_400

**Comment by Grimler91** [comment]
What version of otter-browser do you have installed? This should have been fixed in 1.0.02-7 (https://github.com/termux/x11-packages/commit/544dc80cc341e87c05174761046cc9d90f641616)

Seem to be some dependency missing though from at least my repo, maybe that's the actual issue:

```
$ apt install otter-browser
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 otter-browser : Depends: qt5-qtbase but it is not installable
                 Depends: qt5-qtsvg but it is not going to be installed
                 Depends: qt5-qtxmlpatterns but it is not going to be installed
                 Depends: qt5-qtwebkit but it is not going to be installed
                 Depends: qt5-qtmultimedia but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by Grimler91** [comment]
qt5-qtbase was only uploaded for i686 for some reason in https://github.com/termux/x11-packages/actions/runs/2169250783, so starting a new build for it: https://github.com/termux/x11-packages/actions/runs/2179392660

**Comment by NoNameMan1231** [comment]
> What version of otter-browser do you have installed? This should have been fixed in 1.0.02-7 (https://github.com/termux/x11-packages/commit/544dc80cc341e87c05174761046cc9d90f641616)
> 
> Seem to be some dependency missing though from at least my repo, maybe that's the actual issue:
> 
> ```
> $ apt install otter-browser
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  otter-browser : Depends: qt5-qtbase but it is not installable
>                  Depends: qt5-qtsvg but it is not going to be installed
>                  Depends: qt5-qtxmlpatterns but it is not going to be installed
>                  Depends: qt5-qtwebkit but it is not going to be installed
>                  Depends: qt5-qtmultimedia but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.
> ```

I use the latest version

**Comment by Grimler91** [comment]
Fixed after qt5-qtbase upload and qt5-qtwebkit bump

**Comment by NoNameMan1231** [comment]
> Fixed after qt5-qtbase upload and qt5-qtwebkit bump

Thanks!

**Pull request closed without merging**
