### PR TITLE
add package: glade

### PR DESCRIPTION
**Pull request by Yisus7u7**
I couldn't compile it on my cell phone due to lack of ram memory, but it didn't house bugs.

I can't say for sure this will work, I'll cross my fingers

### CODE REVIEW

**Comment by Yisus7u7** [comment]
@xeffyr Why?

**Comment by suhan-paradkar** [comment]
You need to either disable introspection in extra configure args or you nerd to patch the package...
It tries to run target gobject-introspection

**Comment by Yisus7u7** [comment]
> You need to either disable introspection in extra configure args or you need to patch the package...
> It tries to run target gobject-introspection

Sorry, they weren't used meson properly

**Comment by suhan-paradkar** [comment]
> Sorry, I don't know how to use meson properly

Use 

```bash
TERMUX_PKG_EXTRA_CONFIGURE_ARGS+="-Dintrospection=false" 
```

In your  `build.sh`

**Comment by Yisus7u7** [comment]
> > Sorry, I don't know how to use meson properly
> 
> Use
> 
> ```shell
> TERMUX_PKG_EXTRA_CONFIGURE_ARGS+="-Dintrospection=false" 
> ```
> 
> In your `build.sh`

I hope it works

**Review by xeffyr — CHANGES_REQUESTED** [review]
Patch meson.build to disable tests.
```
../src/meson.build:227:0: ERROR: Can not run test applications in this cross environment.
```

**Comment by Yisus7u7** [comment]
Sorry, I've never used meson, besides, I haven't found anything that explains how to make patches for termux

**Comment by xeffyr** [comment]
> how to make patches for termux

Patching is individual for every package and is a creative work ;) Since Termux is a non-standard platform, you will not find instructions on how to make patches. They simply do not exist. You can be first who make a patch for `glade` to compile it for Termux.

**Comment by Yisus7u7** [comment]
> > how to make patches for termux
> 
> Patching is individual for every package and is a creative work ;) Since Termux is a non-standard platform, you will not find instructions on how to make patches. They simply do not exist. You can be first ever who made a patch for `glade` to compile it for Termux.

Could you provide me with a simple example of a patch?, I am one of those who understands with drawings .

**Comment by xeffyr** [comment]
Sure, here is it: https://github.com/termux/x11-packages/blob/master/packages/libxkbcommon/disable_tests.patch. However what should be removed from glade's meson.build, you should figure out on your own.

Patches are created by utility `diff` in this way:
```
diff -uNr ./original-source-dir/ ./modified-source-dir/ > filename.patch
```

**Comment by Yisus7u7** [comment]
> Sure, here is it: https://github.com/termux/x11-packages/blob/master/packages/libxkbcommon/disable_tests.patch. However what should be removed from glade's meson.build, you should figure out on your own.
> 
> Patches are created by utility `diff` in this way:
> 
> ```
> diff -uNr ./original-source-dir/ ./modified-source-dir/ > filename.patch
> ```

I can't understand it, can you edit and copy the diff generated by GitHub?

**Comment by xeffyr** [comment]
What you can't understand, the meaning of patch file or the fact that you need to find and remove certain code and create a difference file between 2 source directories?

**Comment by Yisus7u7** [comment]
> What you can't understand, the meaning of patch file or the fact that you need to find and remove certain code and create a difference file between 2 source directories?

The second

**Comment by leapofazzam123** [comment]
I tried to compile Glade on Termux, but I got this error:
```
../src/main.c:118:1: error: static declaration of 'open' follows non-static declaration
open (GApplication  *application,
^
/data/data/com.termux/files/usr/include/stdio.h:383:5: note: previous declaration is here
int open(const char*, int, ...);
    ^
```
I also reported it to GNOME Gitlab repo https://gitlab.gnome.org/GNOME/glade/-/issues/522

**Comment by Yisus7u7** [comment]
> I tried to compile Glade on Termux, but I got this error:
> 
> ```
> ../src/main.c:118:1: error: static declaration of 'open' follows non-static declaration
> open (GApplication  *application,
> ^
> /data/data/com.termux/files/usr/include/stdio.h:383:5: note: previous declaration is here
> int open(const char*, int, ...);
>     ^
> ```
> 
> I also reported it to GNOME Gitlab repo https://gitlab.gnome.org/GNOME/glade/-/issues/522

Oh well, expect them to say

**Comment by Yisus7u7** [comment]
@xeffyr
Can I use the diff generated by GitHub commits to create a patch?

**Comment by suhan-paradkar** [comment]
> I also reported it to GNOME Gitlab repo https://gitlab.gnome.org/GNOME/glade/-/issues/522

Well... That's something worth reporting

**Comment by xeffyr** [comment]
> Can I use the diff generated by GitHub commits to create a patch?

You can use diff produced by commands `git diff`, `git format-patch -1 ...` or `diff -uNr src dst`. Diff shown on GitHub is only for visual comparison. Choose what is best suitable in your case. Asking maintainers to create the patch for you is nonsense however. Learn `git`, `diffutils` and `patch` usage.

**Comment by xeffyr** [comment]
Yes, that's a Termux specific issue happening due to NDK headers. `open()` is being somehow declared through stdio header (should be unistd?) and it seems conflict with function declared in main.c.

Should be solvable by renaming function in main.c to something else.

**Comment by xeffyr** [comment]
Issue comes from https://github.com/termux/termux-packages/blob/master/ndk-patches/stdio.h.patch#L60

**Comment by Grimler91** [comment]
> Issue comes from https://github.com/termux/termux-packages/blob/master/ndk-patches/stdio.h.patch#L60

Maybe we can remove the entire tmpdir defintions. I guess it was added because tmpdir used to try to use /tmp, but looks like [bionic's implementation](https://github.com/aosp-mirror/platform_bionic/blob/925431a072737d4c1bbf18f3da7ab24a25486870/libc/bionic/tmpfile.cpp#L93) should work since roughly android 4. It first tries to use /data/local/tmp, and when that fails P_tmpdir which we set to $PREFIX/tmp (and on very new android versions it first even checks for $TMPDIR).

Adding it to my list of things to test.

**Comment by xeffyr** [comment]
Problem is that P_tmpdir is hardcoded into libc. It is a macros:
```
#define P_tmpdir "/tmp/"
```

To change behavior of `tmpfile()`, the whole function needs to be redefined.

**Review by oneemo95 — APPROVED** [review]

**Review by vishnuaq — APPROVED** [review]
**cv no one **

**Comment by leapofazzam123** [comment]
> Yes, that's a Termux specific issue happening due to NDK headers. `open()` is being somehow declared through stdio header (should be unistd?) and it seems conflict with function declared in main.c.
> 
> Should be solvable by renaming function in main.c to something else.

I renamed the function to _open and looks like it's unused

**Comment by leapofazzam123** [comment]
I made some patches:
```diff
--- a/src/main.c	2021-08-15 14:38:19.381711916 +0700
+++ b/src/main.c	2021-08-15 14:36:15.489711908 +0700
@@ -115,7 +115,7 @@
 }
 
 static void
-open (GApplication  *application,
+_open (GApplication  *application,
       GFile        **files,
       gint           n_files,
       const gchar   *hint)
```
```diff
--- a/help/meson.build	2021-08-15 14:43:43.333711935 +0700
+++ b/help/meson.build	2021-08-15 14:36:15.209711908 +0700
@@ -3,9 +3,9 @@
   'legal.xml',
 ]
 
-gnome.yelp(
-  glade_name,
-  sources: sources,
-  media: 'figures/main-window.png',
-  symlink_media: true,
-)
+#gnome.yelp(
+#  glade_name,
+#  sources: sources,
+#  media: 'figures/main-window.png',
+#  symlink_media: true,
+#)

```

**Comment by xeffyr** [comment]
Added in https://github.com/termux/x11-packages/commit/58237f826038040df330f5254132a79ad5de2063. It's unbelievable that 2 simple patches were not submitted within 10 days and still I had to make them myself.

@Yisus7u7 If you still can't accomplish basics (reading the build scripts, using `diff`, etc), I'm suggesting to stick to *package requests*, not pull. I hope you will check the mentioned commit and understand that packaging is not limited to filling metadata fields.

**Comment by leapofazzam123** [comment]
> _Used, check the code more carefully._

Sorry

**Comment by leapofazzam123** [comment]
@xeffyr also looks like your glade doesn't support webkit2gtk widgets

**Comment by xeffyr** [comment]
Well, my variant is based on yours and uses same dependencies:
```
TERMUX_PKG_DEPENDS="atk, fontconfig, freetype, gdk-pixbuf, glib, gtk3, libcairo, libxml2, pango, xsltproc, libglade"
```
There no webkit2gtk specified.

Configure options also don't specify `-Dwebkit2gtk=true` or something like. You can try fixing that in a new PR.

**Comment by Yisus7u7** [comment]
@xeffyr Sorry for that annoyance, I'm just a student, besides I just realized that GitHub has an option to create a patch of the file

**Pull request closed without merging**
