### PR TITLE
add package: caja

### PR DESCRIPTION
**Pull request by Yisus7u7**
Caja is the official file manager of the MATE desktop environment

Screenshot_20211028-201008
Screenshot_20211028-173629

### CODE REVIEW

**Comment by Yisus7u7** [comment]
@xeffyr

I already added the mate-common package and it should work, but it comes out that it is not installed, why?

**Comment by Yisus7u7** [comment]
In a local build from my device the package compiles smoothly.

**Comment by xeffyr** [comment]
> In a local build from my device using termux-build-environment the package compiles smoothly.

local build environment inside Termux != official Termux build environment. Packages may build fine on device but not in our build env image and vice-versa. All development should be done only in our build environment (`docker.io/termux/package-builder`).

**Comment by Yisus7u7** [comment]
Maybe it should work well, the mistake is that it does not find the "mate-common" dependency, and that should not happen.

**Comment by xeffyr** [comment]
Bumping revisions won't suddenly fix the package. You should do a local build and look into log file.

**Comment by xeffyr** [comment]
```
ld: error: undefined symbol: setpwent
>>> referenced by caja-file.c
>>>               caja-file.o:(caja_get_user_names) in archive ../libcaja-private/.libs/libcaja-private.a

ld: error: undefined symbol: getpwent
>>> referenced by caja-file.c
>>>               caja-file.o:(caja_get_user_names) in archive ../libcaja-private/.libs/libcaja-private.a
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [Makefile:1027: caja] Error 1
make[4]: *** Waiting for unfinished jobs....
ld: error: undefined symbol: setpwent
>>> referenced by caja-file.c
>>>               caja-file.o:(caja_get_user_names) in archive ../libcaja-private/.libs/libcaja-private.a

ld: error: undefined symbol: getpwent
```

Patch usage of setpwent/getpwent. Examples on what should be done you could find in `termux-packages` repo.

**Pull request closed without merging**
