### PR TITLE
Add LXQt desktop environment packages

### PR DESCRIPTION
**Pull request by librehat**
This PR adds the "full" LXQt desktop environment to Termux X11.

Note: packages that don't make sense in a non-rooted single-user environment are not included (such as users management and sudo permission). Some plugins might be disabled due to missing dependencies.

### CODE REVIEW

**Comment by suhan-paradkar** [comment]
Whoa man... Great job..

**Comment by WMCB-Tech** [comment]
Finally, a second Desktop Environment for Termux! this could be useful for KDE Users!

**Comment by xeffyr** [comment]
Looks like CI can't download a source archive due to networking issues.
```
curl: (7) Failed to connect to xorg.freedesktop.org port 443: Connection refused
Failed to download https://xorg.freedesktop.org/archive/individual/data/xkeyboard-config/xkeyboard-config-2.32.tar.bz2
```
Will have to merge this pull request and process it manually with fetching sources from mirrors if necessary.

**Comment by Yisus7u7** [comment]
When will it be available?

**Comment by librehat** [comment]
There is a networking issue with freedesktop.org so we'll need to wait for them to become online again (or using a mirror site for xorg packages)

**Comment by xeffyr** [comment]
@librehat I already have the deb files for lxqt, so they will be available for installation soon.

**Comment by Yisus7u7** [comment]
Does that mean that within a couple of hours it will be available? :3

**Comment by xeffyr** [comment]
It is available now.

**Comment by Yisus7u7** [comment]
I finished installing it 3 minutes ago. JAJAJAJ

**Pull request merged**
