### PR TITLE
New Package: SpaceCadetPinball

### PR DESCRIPTION
**Pull request by Yonle**
Continuation of https://github.com/termux/x11-packages/pull/620. This pull is still W.I.P.

### CODE REVIEW

**Comment by Yonle** [comment]
Required Dependency: `timidity++` for converting Midi as WAVE. Needed by SpaceCadetPinball itself

**Comment by Yonle** [comment]
Binary having exec format error.
```
./calcnewt > newton_table.c
/bin/bash: line 1: ./calcnewt: cannot execute binary file: Exec format error
```

Probably due to using Glibc linker instead of Bionic ones. Will made some patch after i found the cause.

**Comment by Yonle** [comment]
I'm still confused.
```
aarch64-linux-android-clang  -fstack-protector-strong -Oz  -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -o calcnewt  calcnewt.o  -lm -ldl     
```

**Comment by xtkoba** [comment]
`calcnewt` needs "hostbuild" because it is executed on the build host (x86_64 GNU/Linux in this case).

**Comment by Yonle** [comment]
> `calcnewt` needs "hostbuild" because it is executed on the build host (x86_64 GNU/Linux in this case).

So now what to do?

**Comment by xtkoba** [comment]
If `calcnewt` is used only intermediately and is never installed (which I guess is the case here because I see it is used for generating C source), then I would patch the build scripts so that it is compiled with `$CC_FOR_BUILD`.

Otherwise, I would use `termux_step_host_build` to generate `calcnewt` and manipulate the build scripts so that it is used in the main build step instead of `./calcnewt`.

Note that there are some cases where cross-building is almost impossible (e.g. `pypy`). But those cases almost always involve some sort of programming language compiler or interpreter, which is not the case here (I suppose).

**Comment by Yonle** [comment]
> 

Maybe you could do a patch to it's build script.

**Comment by Yonle** [comment]
Alright. Porting continued.

**Pull request closed without merging**
