### PR TITLE
Add termux-terminal

### PR DESCRIPTION
**Pull request by AnGelXoG**
a customizable fast terminal

I already fixed the license problem :)

### CODE REVIEW

**Comment by Grimler91** [comment]
* The copyright headers have not been restored

* Why should we package your fork of kermit instead of kermit? Are there added features? (hard to tell since git history has been reset)

**Comment by AnGelXoG** [comment]
La verdad si e modificado los archivos

**Comment by AnGelXoG** [comment]
The truth is, I have modified little things

**Comment by AnGelXoG** [comment]
I also had to edit the makefile for a quick and clean installation since what came did not install in termux

**Comment by Grimler91** [comment]
> I also had to edit the makefile for a quick and clean installation since what came did not install in termux

Sounds like those modifications could be added to kermit, either as a patch in (a future) kermit package in x11-packages, or as a PR to https://github.com/orhun/kermit. 

Try to make a PR to add kermit as a package instead, using the original repository for source is preferred unless there are valid reasons for using a fork (for example if the fork is better maintained).

Also note that your repository still does not contain the copyright headers in termux.c and termux.h, so the original author is not credited. Again, see [the GPL license text](https://www.gnu.org/licenses/gpl-3.0.en.html), in particular section 5. Conveying Modified Source Versions, and for example [this stackexchange question](https://stackoverflow.com/questions/4475319/how-to-rebrand-copyright-a-forked-project-gnu-gpl).

**Comment by AnGelXoG** [comment]
are forks acceptable?

**Comment by Yisus7u7** [comment]
> are forks acceptable?

1- you have to leave credits if it is a fork.

2- For a fork to be accepted it must implement new functions or very large changes.

**Pull request closed without merging**
