### PR TITLE
qt5-qtbase: Enable OpenGL

### PR DESCRIPTION
**Pull request by xtkoba**
Closes #576.

### CODE REVIEW

**Comment by xtkoba** [comment]
@librehat I would humbly ask you as the maintainer to review this PR.

**Comment by librehat** [comment]
No this would break Qt 5 builds completely.

By default you don't have OpenGL drivers in Termux. This option would ask Qt to use OpenGL for rendering which would just fail to render anything.

**Comment by xtkoba** [comment]
Oh, thanks!

**Comment by Yisus7u7** [comment]
@xtkoba @librehat 

I installed the artifact and it works very well.

### Using OpenGL
Screenshot_20220306-131433

### No OpenGL 
Screenshot_20220306-131341

**Comment by Yisus7u7** [comment]
It seems that if we can use Qt with OpenGL without problems!

**Comment by librehat** [comment]
Interesting, will check this

**Comment by Yisus7u7** [comment]
> Interesting, will check this

Yes

**Pull request closed without merging**
