### PR TITLE
Adding xorg-server package with full Xorg and dummy driver

### PR DESCRIPTION
**Pull request by twaik**
I think it will be useful. Also for now I'm trying to output image from Xorg to Activity surface via shared memory.

### CODE REVIEW

**Comment by xeffyr** [comment]
Is there any "frontend" to test it ?

**Comment by twaik** [comment]
I can add xf86-video-fbdev, xf86-input-evdev, xf86-input mtev for the root users. Is it needed?

**Comment by xeffyr** [comment]
xf86-video-fbdev will conflict with Android's GUI.

**Comment by twaik** [comment]
As I mentioned before it should be used with root. And root users can shutdown surfaceflinger process or use Xorg from recovery with /data and /system partitions mounted.

**Comment by twaik** [comment]
> xf86-video-fbdev will conflict with Android's GUI.
xf86-input-evdev and xf86-input-mtev can notbe used without root too.

**Comment by xeffyr** [comment]
Okay, you can open a PR for them.

**Comment by xeffyr** [comment]
Compilation fails for `xorg-server`. Error:
```
/home/builder/.termux-build/xorg-server/src/hw/xfree86/common/compiler.h:533:6: error: cast to 'volatile unsigned char *' from smaller integer type 'unsigned int'
      [-Werror,-Wint-to-pointer-cast]
    *(volatile unsigned char *) (((unsigned PORT_SIZE) (port)) + IOPortBase) =
     ^
/home/builder/.termux-build/xorg-server/src/hw/xfree86/common/compiler.h:540:6: error: cast to 'volatile unsigned short *' from smaller integer type 'unsigned int'
      [-Werror,-Wint-to-pointer-cast]
    *(volatile unsigned short *) (((unsigned PORT_SIZE) (port)) + IOPortBase) =
     ^
/home/builder/.termux-build/xorg-server/src/hw/xfree86/common/compiler.h:547:6: error: cast to 'volatile unsigned int *' from smaller integer type 'unsigned int'
      [-Werror,-Wint-to-pointer-cast]
    *(volatile unsigned int *) (((unsigned PORT_SIZE) (port)) + IOPortBase) =
     ^
/home/builder/.termux-build/xorg-server/src/hw/xfree86/common/compiler.h:554:13: error: cast to 'volatile unsigned char *' from smaller integer type 'unsigned int'
      [-Werror,-Wint-to-pointer-cast]
    return *(volatile unsigned char *) (((unsigned PORT_SIZE) (port)) +
            ^
/home/builder/.termux-build/xorg-server/src/hw/xfree86/common/compiler.h:561:13: error: cast to 'volatile unsigned short *' from smaller integer type 'unsigned int'
      [-Werror,-Wint-to-pointer-cast]
    return *(volatile unsigned short *) (((unsigned PORT_SIZE) (port)) +
            ^
/home/builder/.termux-build/xorg-server/src/hw/xfree86/common/compiler.h:568:13: error: cast to 'volatile unsigned int *' from smaller integer type 'unsigned int'
      [-Werror,-Wint-to-pointer-cast]
    return *(volatile unsigned int *) (((unsigned PORT_SIZE) (port)) +
```

Can be solved by adding `-Wint-to-pointer-cast` to CFLAGS.

But for x86_64 it fails anyway:
```
  CCLD     libXFree86.la
os-support/.libs/libxorgos.a(lnx_video.o):lnx_video.c:function xf86EnableIO: error: undefined reference to 'ioperm'
os-support/.libs/libxorgos.a(lnx_video.o):lnx_video.c:function xf86EnableIO: error: undefined reference to 'iopl'
os-support/.libs/libxorgos.a(lnx_video.o):lnx_video.c:function xf86EnableIO: error: undefined reference to 'ioperm'
os-support/.libs/libxorgos.a(lnx_video.o):lnx_video.c:function xf86EnableIO: error: undefined reference to 'ioperm'
os-support/.libs/libxorgos.a(lnx_video.o):lnx_video.c:function xf86DisableIO: error: undefined reference to 'iopl'
os-support/.libs/libxorgos.a(lnx_video.o):lnx_video.c:function xf86DisableIO: error: undefined reference to 'ioperm'
clang70: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:809: recipe for target 'libXFree86.la' failed
```

**Comment by twaik** [comment]
You can try to build it again.

**Comment by xeffyr** [comment]
Again error, but different:
```
os-support/.libs/libxorgos.a(vidmem.o):vidmem.c:function xf86InitVidMem: error: undefined reference to 'xf86OSInitVidMem'
clang70: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by twaik** [comment]
Got the same error. Fixed.
P.S. Are you russian?

**Comment by xeffyr** [comment]
Seems okay now.

> P.S. Are you russian?

I'm ukrainian.

**Comment by twaik** [comment]
> I'm ukrainian.

Cool. Me too :)

**Comment by xeffyr** [comment]
Packages are in 'testing' X11 repo.
```
pkg install x11-testing-repo
pkg install xorg-server xf86-input-evdev xf86-input-mtev xf86-video-dummy xf86-video-fbdev
```

**Pull request merged**
