### PR TITLE
new package: nxengine

### PR DESCRIPTION
**Pull request by xeffyr**

### CODE REVIEW

**Comment by Yonle** [comment]
By the way, When i'm building this in Builder container got this error:
Screenshot_2021_0820_000408

And this error is never happend when building in actual android device & native termux.

**Comment by xeffyr** [comment]
By the way, I have already compiled it for aarch64. Just your patch is *wrong* as build.sh.

**Comment by Yonle** [comment]
Ah i see. Well there's a success process as i can see now. Good luck and thanks 👍

Sorry for a BIG mistake that i did before.

**Comment by Grimler91** [comment]
> And this error is never happend when building in actual android device & native termux.

It is an issue with the cross-compilation. As can be seen it used the program `g++` instead of `aarch64-linux-android-clang++` and then tried to link ubuntu's x86_64 libraries together with android aarch64 libraries. [@xeffyr fixed it here](https://github.com/termux/x11-packages/pull/419/files#diff-9e0f17d67bbe87e96e753c4c1fae053e00458fb4a371906d012b471860e2059eR8-R11).

**Comment by Yonle** [comment]
The latest changes in NXEngine branch repo wants Doukutsu.exe version v1.0.0.6 to work.

The requested resource is there (EXE installation): https://aeongenesis.net/download/cavestory

**Comment by xeffyr** [comment]
Yes, it requires the `Doukutsu.exe`, otherwise it exists (if pressed ESC) or shows error that it can't find `Doukutsu.exe`.

**Pull request merged**
