### PR TITLE
add package : lxtask

### PR DESCRIPTION
**Pull request by Yisus7u7**
Lxtask is a taskmanager for lxde

### CODE REVIEW

**Comment by Yisus7u7** [comment]
@xeffyr why?

**Comment by xeffyr** [comment]
@Yisus7u7 Why are you doing `autoreconf -fi`? Is that because typical solution for missing `./configure`?

I'm suggesting to look the sources next time, instead of using whatever sources of common Termux package recipes. They will work for some packages. For others - not.

Solution is `./autogen.sh`. Btw, you can look it to learn why `autoreconf` isn't enough.

**Comment by xeffyr** [comment]
I'm fixing that myself now, but really pull request authors should take care about what they are submitting, unless issue introduced on our side.

**Comment by Yisus7u7** [comment]
Thank you very much, then I will make requests to extract more things that I could compile, I already begin to understand how this works

**Pull request merged**
