### PR TITLE
add package: wayland

### PR DESCRIPTION
**Pull request by suhan-paradkar**

### CODE REVIEW

**Comment by xeffyr** [comment]
What's the purpose of adding Wayland server?

**Comment by suhan-paradkar** [comment]
It seems that  GNOME and KDE are expected to be ported to it.

**Comment by WMCB-Tech** [comment]
I don't think GNOME/KDE should be ported here as it may require such heavy dependencies, and GNOME relies on systemd?,

**Comment by xeffyr** [comment]
@suhan-paradkar Direct graphical output is not supported, so `xorg`, `wayland` or similar are useless. Graphical output is done over VNC or to external X server backed by Android application.

In order to have Wayland server working, this Termux add-on has to be finished: https://github.com/termux/termux-x11. Also see `disabled-packages/xwayland`.

**Pull request closed without merging**
