### PR TITLE
sdl2: update to 2.0.20

### PR DESCRIPTION
**Pull request by RazyRabbit**
This is my first termux related pull request! 🥳

### CODE REVIEW

**Comment by RazyRabbit** [comment]
🥰

**Comment by xtkoba** [comment]
So it turns out that `configure.patch` does not need to be modified at all.

**Comment by RazyRabbit** [comment]
Yeah... it was my fault... i accidentaly cloned from master branch of SDL2... the configure script was different in size and layout...

**Review by xtkoba — COMMENTED** [review]
If you are already familiar with Git, then please clean up the commits and squash them into one. If not, we will do it on our side.

**Comment by RazyRabbit** [comment]
Okay! wait!

**Comment by RazyRabbit** [comment]
done!

**Comment by RazyRabbit** [comment]
@xtkoba DONE!

**Review by xtkoba — APPROVED** [review]
LGTM. :+1:

**Comment by RazyRabbit** [comment]
YAY! 🎉

**Pull request merged**
