### PR TITLE
add package : lxappearance 

### PR DESCRIPTION
**Pull request by Yisus7u7**
lxappearance It is an independent gtk theme manager

### CODE REVIEW

**Comment by xeffyr** [comment]
@Yisus7u7 Could you use separate branches when creating pull request or at least do reset and pull for the latest `master` branch and then apply commits?

**Comment by Yisus7u7** [comment]
> @Yisus7u7 Could you use separate branches when creating pull request or at least do git reset and pull for the latest `master` branch and then apply commits?

Excuse me, I don't know how to do it, could you give me an example?, please

**Comment by xeffyr** [comment]
Creating new branch "my-branch" and switching to it:
```
git checkout -b my-branch
```

Switching to branch `master`:
```
git checkout master
```

Pulling changes from remote into current branch:
```
git pull
```

Pull and rebase current changes on latest remote branch:
```
git pull --rebase
```

Resetting current branch going 25 commits back:
```
git reset --hard HEAD~25
```

Rebase changes in current branch on branch `master`:
```
git rebase master
```

Add another upstream url for push/pull:
```
git remote add termux-official https://github.com/termux/termux-packages
```

Example command of "fixing" the `master` branch of your fork. Backup your changes before doing this.
```
git checkout master
git reset --hard HEAD~10
git remote add termux https://github.com/termux/termux-packages
git fetch termux
git merge termux/master
git push --force
```

***

I have provided some commands above. Pick ones that you need in correct order. Before copy-pasting, ensure that you know what they doing. Learn git, begin with https://guides.github.com/introduction/git-handbook/ and https://git-scm.com/docs/gittutorial.

So what you need to do:
1. Ensure you are on the branch `master`.
2. Cancel the **all** your commits that do not match termux/termux-packages@master
3. Pull all changes made in termux/termux-packages@master into your fork.
4. Create new branch, e.g. `add-package-1`.
5. Make changes and commit them.
6. Create pull request or switch branch in current one.

**Comment by Yisus7u7** [comment]
@xeffyr The compilation failed in "make install", the error is because to run make install you have to enter the folder "src", as I specify that in the build.sh?

**Comment by xeffyr** [comment]
Fails because "nonet" is not found.
```
make[1]: Entering directory '/home/builder/.termux-build/lxappearance/src/man'
nonet http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl lxappearance.xml
/bin/bash: nonet: command not found
make[1]: [Makefile:536: lxappearance.1] Error 127 (ignored)
make[2]: Entering directory '/home/builder/.termux-build/lxappearance/src/man'
make[2]: Nothing to be done for 'install-exec-am'.
nonet http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl lxappearance.xml
/bin/bash: nonet: command not found
make[2]: [Makefile:536: lxappearance.1] Error 127 (ignored)
 /usr/bin/mkdir -p '/data/data/com.termux/files/usr/share/man/man1'
 /usr/bin/install -c -m 644 ./lxappearance.1 '/data/data/com.termux/files/usr/share/man/man1'
/usr/bin/install: cannot stat './lxappearance.1': No such file or directory
```

**Comment by Yisus7u7** [comment]
@xeffyr I compiled it without using nonet, just run : 
```
cd src/
make install
```
And it works smoothly, how do I pass that argument?

**Comment by xeffyr** [comment]
Override step `termux_step_make_install`.

https://github.com/termux/termux-packages/wiki/Creating-new-package#table-of-available-build-step-overrides...

**Comment by Yisus7u7** [comment]
> Override step `termux_step_make_install`.
> 
> https://github.com/termux/termux-packages/wiki/Creating-new-package#table-of-available-build-step-overrides...

```bash
termux_step_make_install() {
           make
           cd ./src
           make install 
} 
```

So is it right or do I make a mistake there?

**Comment by xeffyr** [comment]
Why you are doing make in `termux_step_make_install`. Open https://github.com/termux/termux-packages/wiki/Creating-new-package#table-of-available-build-step-overrides and check the step execution order.

`make` is already ran by `termux_step_make`. It doesn't matter whether it is in build.sh or not. `build-package.sh` defines all possible steps with reasonable defaults.

**Pull request merged**
