### PR TITLE
add package: quassel (#721, #710)

### PR DESCRIPTION
**Pull request by JesusChapman**
Screenshot_20220403-165941

### CODE REVIEW

**Comment by Yisus7u7** [comment]
@xtkoba Why?, on the device I didn't get that.

**Comment by z8512** [comment]
@Yisus7u7 can you check what's causing this error in Github Actions logs?

By the way, thank you very very much. I really appreciate your contribution ❤.  

Can you share the .deb file so I can install now, since you had built it successfully in termux 🤗

**Comment by Yisus7u7** [comment]
I myself have taken care of many problems, only here I do not know what to do, since the compilation on the device does not have those problems.

**Comment by Yonle** [comment]
> I myself have taken care of many problems, only here I do not know what to do, since the compilation on the device does not have those problems.

Note that cross-compiling is different. 
At this time, I may look at `qt` build script.

**Comment by Yisus7u7** [comment]
I can't currently take care of this, here's why https://github.com/Yisus7u7/Yisus7u7

**Pull request closed without merging**
