### PR TITLE
Add package : materia-gtk-theme

### PR DESCRIPTION
**Pull request by Yisus7u7**
Materia is a very nice gtk theme..

### CODE REVIEW

**Comment by Yisus7u7** [comment]
@suhan-paradkar
Why when I open a pull request do I get that?

**Comment by suhan-paradkar** [comment]
> @suhan-paradkar
> Why when I open a pull request do I get that? 

It's always recommended to create a new branch for a new PR....
Also.. It is recommended that you do NOT change the master branch....

**Comment by Yisus7u7** [comment]
Sorry my hazing, how do I create a new branch?

**Comment by suhan-paradkar** [comment]
> Sorry my hazing, how do I create a new branch? 
See this... as a guide...
https://github.com/Kunena/Kunena-Forum/wiki/Create-a-new-branch-with-git-and-manage-branches

**Comment by suhan-paradkar** [comment]
Also... it is always better if you rebase against master...(if you are using other branches)

**Comment by Yisus7u7** [comment]
Thank you

**Comment by suhan-paradkar** [comment]
> Thank you

For this PR ... you can't do anything...
Use different branches for next PRs

**Comment by Yisus7u7** [comment]
Ok bro, thanks for your help

**Pull request closed without merging**
