### PR TITLE
add package: lxqt-composer-settings

### PR DESCRIPTION
**Pull request by Yisus7u7**
Screenshot_20220329-143045

I know that these types of applications do not comply with the rules of termux as it is an app created by a third party, but I would like to make an exception. 

I created this application as a basic module for lxqt, so that the installation has a composer active by default, you can use xcompmgr or picom as the engine.

I built this application as an lxqt module, since lxqt by default doesn't come with a compose manager installed, many inexperienced termux users don't know about this, so they think lxqt is broken, since it doesn't If there is a layout manager active, it can get stuck at times, and terminal emulators get stuck or don't display the full text when typing.

I made this application to facilitate the use of this desktop for novice users.

Thanks for reading this.

### CODE REVIEW

**Comment by Yisus7u7** [comment]
The application just started,It still needs to be added and changed in it but it is already easy to use and stable.

**Comment by xtkoba** [comment]
> I know that these types of applications do not comply with the rules of termux as it is an app created by a third party,

AFAIK there are no such rules.

**Comment by xtkoba** [comment]
@Yisus7u7 Please read https://www.gnu.org/licenses/gpl-howto.en.html. The following condition is not met:

> Give each file the proper copyright notices. Make sure to clearly identify which versions of the license users can use.

**Comment by Yisus7u7** [comment]
> > I know that these types of applications do not comply with the rules of termux as it is an app created by a third party,
> 
> AFAIK there are no such rules.

Well, from what I had understood to add a package to Termux should be recognized or very useful q

**Comment by Yisus7u7** [comment]
But if you can add it, then thank you!

**Comment by Yisus7u7** [comment]
> @Yisus7u7 Please read https://www.gnu.org/licenses/gpl-howto.en.html. The following condition is not met:
> 
> > Give each file the proper copyright notices. Make sure to clearly identify which versions of the license users can use.

Do you mean putting a license comment on the main files?

**Comment by xtkoba** [comment]
> Do you mean putting a license comment on the main files?

Exactly.

**Comment by Yisus7u7** [comment]
@xtkoba Done.

**Comment by Yisus7u7** [comment]
Screenshot_20220331-164843

@xtkoba I already tried it, it works excellently. 

And I added the license manifests to some files

**Pull request merged**
