### PR TITLE
Add package: Mate Desktop

### PR DESCRIPTION
**Pull request by suhan-paradkar**

### CODE REVIEW

**Comment by suhan-paradkar** [comment]
Currently, this is it... I am currently facing issues compiling mate-settings-daemon.. will update when it is done...

**Comment by suhan-paradkar** [comment]
Compiling mate-settings-daemon in the docker image gives the following output
```
Making all in mate-settings-daemon                              make[2]: Entering directory '/home/builder/.termux-build/mate-settings-daemon/build/mate-settings-daemon'                         GEN      mate-settings-client.h                                 GEN      mate-settings-manager-glue.h                         /bin/bash: dbus-binding-tool: command not found                 /bin/bash: dbus-binding-tool: command not found                 make[2]: *** [Makefile:1011: mate-settings-manager-glue.h] Error 127                                                            make[2]: *** Waiting for unfinished jobs....                    make[2]: *** [Makefile:1014: mate-settings-client.h] Error 127  make[2]: Leaving directory '/home/builder/.termux-build/mate-settings-daemon/build/mate-settings-daemon'                        make[1]: *** [Makefile:495: all-recursive] Error 1              make[1]: Leaving directory '/home/builder/.termux-build/mate-settings-daemon/build'                                             make: *** [Makefile:427: all] Error 2
```
It seems to me that dbus-binding-tool is not present in the host.. will try to fix that

**Comment by suhan-paradkar** [comment]
I will add those packages in a separate PR .. well ... I was not able to solve the problem though...

**Comment by xeffyr** [comment]
Why not do that in this PR? I won't merge incomplete desktop environment package sets.

Docker image needs package `libdbus-glib-1-dev-bin`. I can add it to setup-ubuntu.sh, update Docker image and then this pull request will just require rebase.

**Comment by suhan-paradkar** [comment]
Ok... Then I will add those to this PR after you add that to `setup-ubuntu.sh`

**Comment by xeffyr** [comment]
New Docker image has been pushed You can update pull request now.

**Review by xeffyr — APPROVED** [review]

**Comment by Yisus7u7** [comment]
When will it be available?

**Comment by Yisus7u7** [comment]
Sorry, I'm excited

**Comment by Yisus7u7** [comment]
Screenshot_20210603-155426
@suhan-paradkar 
._.

**Pull request merged**
