### PR TITLE
add package : gtk2-engines-murrine

### PR DESCRIPTION
**Pull request by Yisus7u7**
This is just a test, I don't know if it works.

### CODE REVIEW

**Comment by Yisus7u7** [comment]
If it worked  🙂

**Comment by xeffyr** [comment]
> I don't know if it works

I don't know either and therefore kindly request to **test things before opening pull request**. Don't expect that I will manually install and run everything. In fact, I even don't use x11 packages at all for now.

**Comment by Yisus7u7** [comment]
> 

I do not have a computer to test these packages, there are compilation dependencies that are not in termux or weigh a lot, so whenever I do a PR that I do not know if it works, I will warn you in a comment.

**Comment by xeffyr** [comment]
> I do not have a computer to test these packages

Test = verify that package is working in Termux, not computer... If you have installed the package and it worked, then ok.

**Pull request merged**
