### PR TITLE
Add package:libmatekbd

### PR DESCRIPTION
**Pull request by suhan-paradkar**
I will be adding other mate components to this PR one by one..

### CODE REVIEW

**Comment by suhan-paradkar** [comment]
I don't know what caused that error.. @xeffyr .. any idea?

**Comment by librehat** [comment]
Looks like the host was trying to execute the target binary

**Comment by suhan-paradkar** [comment]
> Looks like the host was trying to execute the target binary

Is there any way to stop it?

**Comment by librehat** [comment]
i believe you want to make it use the host shell interpreter instead of the one in `$TERMUX_PREFIX`

**Comment by suhan-paradkar** [comment]
> i believe you want to make it use the host shell interpreter instead of the one in `$TERMUX_PREFIX`

You mean set TERMUX_PKG_HOSTBUILD=true?

**Comment by xeffyr** [comment]
> TERMUX_PKG_HOSTBUILD=true

Host build is a building package for the host - Ubuntu x86_64. Usually needed for obtaining host binaries.

In your case, the package should be patched to use `/usr/bin/glib-genmarshal` instead of one in Termux. *Packages are cross-compiled. You can't use build tools from Termux but only from Ubuntu.*

**Comment by xeffyr** [comment]
@suhan-paradkar What you are trying to do? `glib-bin` is **useless there** because it is a target package and thus *not executable* under Docker.

I have suggested you to patch the package already...

**Comment by xeffyr** [comment]
Here is a what should be applied:
```
diff -uNr libmatekbd-1.25.0/libmatekbd/Makefile.am libmatekbd-1.25.0.mod/libmatekbd/Makefile.am
--- libmatekbd-1.25.0/libmatekbd/Makefile.am	2020-08-18 16:31:05.000000000 +0300
+++ libmatekbd-1.25.0.mod/libmatekbd/Makefile.am	2021-05-18 14:44:16.231681358 +0300
@@ -103,7 +103,7 @@
 
 DISTCLEANFILES = $(gsettings_SCHEMAS)
 
-GLIB_GENMARSHAL = $(shell pkg-config --variable=glib_genmarshal glib-2.0)
+GLIB_GENMARSHAL = glib-genmarshal
 
 matekbd-indicator-marshal.h: matekbd-indicator-marshal.list
 	$(AM_V_GEN)$(GLIB_GENMARSHAL) --prefix=matekbd_indicator $(srcdir)/matekbd-indicator-marshal.list --header > $@
```

**Review by xeffyr — APPROVED** [review]
I'm merging this now. However if you are working on a MATE desktop port, please submit all related packages in one pull request.

**Pull request merged**
