### PR TITLE
libvte: Revert to 0.62.2

### LINKED ISSUE #537: terminal-xfce4 closes when opened
### Problem description

**the xfce4 terminal closes when opened, I do not know what the problem would be since it affects kermit terminal since they both close on April they do not show any error is the weirdest thing : l**

### What steps will reproduce the bug?

terminals are closed

### What is the expected behavior?

Q work xd

### System information

termux-info:

```

```

### PR DESCRIPTION
**Pull request by xtkoba**
Hopefully fixes #537.

Supersedes #538.

### CODE REVIEW

**Comment by xtkoba** [comment]
Forgot to revbump revdeps.

**Comment by Yisus7u7** [comment]
Don't worry about the error in aarch64, it's just an error while downloading a file in the workflow

**Comment by Yisus7u7** [comment]
> Hopefully fixes #537.
> 
> Supersedes #538.

Thanks!!

**Comment by Yisus7u7** [comment]
> > Hopefully fixes #537.
> > Supersedes #538.
> 
> Thanks!!

Screenshot_20211216-224618

**Comment by NoNameMan1231** [comment]
#553 maybe problem will fix cause I update xfce4.terminal

**Review by xeffyr — APPROVED** [review]

**Pull request merged**
