### PR TITLE
add zeitgeist for midori

### PR DESCRIPTION
**Pull request by RossComputerGuy**

### CODE REVIEW

**Comment by xeffyr** [comment]
> TERMUX_PKG_DEPENDS="gtk3

X11 packages have to be added to https://github.com/termux/x11-packages only.

**Comment by xeffyr** [comment]
Requires **gobject-introspection**.

**Comment by RossComputerGuy** [comment]
gobject-introspection is a build dependency, not needed for using zeitgeist.

**Comment by xeffyr** [comment]
> gobject-introspection is a build dependency

Okay, will look at editing configure script then.

**Comment by RossComputerGuy** [comment]
It looks like build dependency python-rdflib is needed too.

**Comment by xeffyr** [comment]
`python-rdflib` will be available after updating docker image.

**Comment by xeffyr** [comment]
Fixed docker image. Now there compilation errors:
```
make[5]: Entering directory '/home/builder/.termux-build/zeitgeist/src/extensions/fts++'
  CXX      controller.o
  CXX      fts.o
  CXX      indexer.o
  CXX      task.o
  CXX      stringutils.o
  CC       zeitgeist-fts.o
  GEN      org.gnome.zeitgeist.SimpleIndexer.service
  GEN      zeitgeist-fts.service
controller.cpp:131:19: error: cannot cast from type 'gboolean (ZeitgeistFTS::Controller::*)()' to pointer type 'GSourceFunc' (aka 'int (*)(void *)')
      g_idle_add ((GSourceFunc) &Controller::ProcessTask, this);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
indexer.cpp:685:13: error: cannot cast from type 'gboolean (ZeitgeistFTS::Indexer::*)()' to pointer type 'GSourceFunc' (aka 'int (*)(void *)')
            (GSourceFunc) &Indexer::ClearFailedLookupsCb, this);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[5]: *** [Makefile:680: controller.o] Error 1
```

**Comment by RossComputerGuy** [comment]
It looks like some systemd stuff was generated so if there's a configure option to disable systemd support then we should use it.

**Comment by RossComputerGuy** [comment]
I noticed configure checks for valac so Im trying to build zeitgeist with valac installed. Maybe that'll fix everything.

**Pull request closed without merging**
