### PR TITLE
Polybar : Updated to 3.6.1

### PR DESCRIPTION
**Pull request by NoNameMan1231**

### CODE REVIEW

**Comment by NoNameMan1231** [comment]
@xtkoba  want to ask why patch will be ignored...

**Comment by xtkoba** [comment]
Current context of failure:

```
Applying patch: tmpdir.patch
The text leading up to this was:
--------------------------
|diff -uNr ./polybar/src/ipc.cpp ./polybar.mod/src/ipc.cpp
|--- ./polybar/src/ipc.cpp 2019-04-03 08:32:20.000000000 +0300
|+++ ./polybar.mod/src/ipc.cpp     2019-07-10 22:14:11.763825428 +0300
--------------------------
File to patch:
Skip this patch? [y]
1 out of 1 hunk ignored
```

This is because our build system invokes `patch` command with `-p1` option. As a result, in the above case `patch` attempts to find `polybar.mod/src/ipc.cpp` which does not exist.

A workaround is to remove leading `./` from file names.

**Comment by NoNameMan1231** [comment]
I think the patch must be deleted since no such file there...

**Comment by NoNameMan1231** [comment]
@xtkoba  don't merge it till I found all hardcoded path...

**Comment by Grimler91** [comment]
> I think the patch must be deleted since no such file there...

The path is passed as a compiler option now instead: https://github.com/polybar/polybar/blob/master/cmake/02-opts.cmake#L19

**Comment by NoNameMan1231** [comment]
> > I think the patch must be deleted since no such file there...
> 
> The path is passed as a compiler option now instead: https://github.com/polybar/polybar/blob/master/cmake/02-opts.cmake#L19

Thanks! I will try to fix them when I have time... Currently busy now

**Comment by xtkoba** [comment]
I believe this is almost ready to merge. Please squash the commits.

**Comment by NoNameMan1231** [comment]
Done!

**Comment by NoNameMan1231** [comment]
`--  Module support:
-- [ ]   alsa
-- [X]   curl (7.82.0)
-- [ ]   i3`

From here we can know if module doesn't enable. Can I use `-DENABLE_I3=ON` at cmake flag in install.sh

**Comment by xtkoba** [comment]
If you mean `build.sh` by `install.sh`, then try:

```bash
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DENABLE_I3=ON
"
```

though not sure if working.

**Comment by NoNameMan1231** [comment]
```
Downloading https://www.zlib.net/zlib-1.2.11.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Failed to download https://www.zlib.net/zlib-1.2.11.tar.xz
``` 

Opps we need to update zlib (to v1.2.12)first

**Comment by Grimler91** [comment]
Rebase against master branch and that problem should be solved

**Comment by NoNameMan1231** [comment]
ipc.h not founded. Let me rolling back first...

**Comment by NoNameMan1231** [comment]
I think I done ..

**Comment by NoNameMan1231** [comment]
How to squash it?

**Comment by NoNameMan1231** [comment]
Good , i broke all things...

**Comment by wmcbtech30** [comment]
> How to squash it?

@NoNameMan1231 Use `git rebase -i` and squash specific commits from `pick` to `squash`

https://www.git-tower.com/learn/git/faq/git-squash/

**Pull request closed without merging**
