### PR TITLE
new package: wxwidgets

### PR DESCRIPTION
**Pull request by xtkoba**
Closes termux/termux-packages#7729.

### CODE REVIEW

**Comment by Yisus7u7** [comment]
You have to disable webkit and a few other things

**Comment by xtkoba** [comment]
@Yisus7u7 You seem to have succeeded in building wxWidgets on device. Any suggestions in detail are welcome. Thanks!

**Comment by Yisus7u7** [comment]
> @Yisus7u7 You seem to have succeeded in building wxWidgets on device. Any suggestions in detail are welcome. Thanks!

You're welcome, we're here to help us

**Comment by Yisus7u7** [comment]
@xtkoba I see that you are compiling wxwidges with webkit, will that work?

**Comment by xtkoba** [comment]
I believe WebKit support is disabled. From build log:

```
2021-12-21T05:46:50.3097684Z configure: WARNING: webkit2gtk not found, falling back to webkitgtk
2021-12-21T05:46:50.3228331Z configure: WARNING: webkitgtk not found.
2021-12-21T05:46:50.3231896Z configure: WARNING: WebKit not available, disabling wxWebView
```

**Comment by Yisus7u7** [comment]
> I believe WebKit support is disabled. From build log:
> 
> ```
> 2021-12-21T05:46:50.3097684Z configure: WARNING: webkit2gtk not found, falling back to webkitgtk
> 2021-12-21T05:46:50.3228331Z configure: WARNING: webkitgtk not found.
> 2021-12-21T05:46:50.3231896Z configure: WARNING: WebKit not available, disabling wxWebView
> ```

Oh, ok

**Review by xeffyr — APPROVED** [review]

**Comment by tigran123** [comment]
Interesting, in that case maybe wxMaxima could be added as well...
I have wxMaxima running under proot in Debian/ARM, but maybe it could also run directly in termux-x11.

**Pull request merged**
